import os

image_dim = (160, 200)
BLOCK_DIMS = (40, 50, 3)
NUM_OF_BLOCKS = 16

VANILLA_HIDDEN_LAYER_SIZE = 1000

MULTILAYER_HIDDEN1_SIZE = 3200
MULTILAYER_HIDDEN2_SIZE = 1600
MULTILAYER_HIDDEN_LAYER_SIZE = 1000

demo_loader_params = {'batch_size': 1}

DEMOS_VIDEO_DIR = "demo_videos"

DEMO_VANILLA_MODEL_DIR_PATH = os.path.join("demo_models", "vanilla")
DEMO_MULTILAYER_MODEL_DIR_PATH = os.path.join("demo_models", "multilayer")

DEMO_CONV2_MODEL_PATH = os.path.join("demo_models", "conv2.pt")
DEMO_CONV3_MODEL_PATH = os.path.join("demo_models", "conv3.pt")
DEMO_CONV4_MODEL_PATH = os.path.join("demo_models", "conv4.pt")
DEMO_CONV5_MODEL_PATH = os.path.join("demo_models", "conv5.pt")
DEMO_VAE_MODEL_PATH = os.path.join("demo_models", "vae.pt")


VANILLA_MODEL_PATH_DIR = ""
VANILLA_MODEL_CHECKPOINTS_PATH_DIR = ""
VANILLA_MODEL_RESULTS_DIR_PATH = ""

MULTILAYER_MODEL_PATH_DIR = ""
MULTILAYER_MODEL_CHECKPOINTS_PATH_DIR = ""
MULTILAYER_MODEL_RESULTS_DIR_PATH = ""

CONVAE4_MODEL_PATH = ""
CONVAE4_MODEL_CHECKPOINTS_PATH = ""
CONVAE4_MODEL_RESULTS_DIR_PATH = ""
CONVAE4_MODEL_PATH_DIR = ""

CONVAE5_MODEL_PATH = ""
CONVAE5_MODEL_CHECKPOINTS_PATH = ""
CONVAE5_MODEL_RESULTS_DIR_PATH = ""
CONVAE5_MODEL_PATH_DIR = ""

VAE_MODEL_PATH = ""
VAE_MODEL_CHECKPOINTS_PATH = ""
VAE_MODEL_RESULTS_DIR_PATH = ""
VAE_MODEL_PATH_DIR = ""
